application: touch-login
version: interim-1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 0d 0h

handlers:
- url: /_ah/spi/.*
  script: api.TouchLoginAPI.APPLICATION
  secure: always
- url: /test/.*
  script: TestClient.main.app
- url: /.*
  script: webServer.webServer.app

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: ssl
  version: latest

